/**
 * ABI for ReverieWorldInstance.sol (facade + libraries)
 */
export const WORLD_INSTANCE_ABI = [
  {
    name: "owner",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    name: "config",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "llmPlatform", type: "address" },
      { name: "jsonPlatform", type: "address" },
      { name: "llmAgentId", type: "uint256" },
      { name: "jsonAgentId", type: "uint256" },
      { name: "webParseAgentId", type: "uint256" },
      { name: "subcommitteeSize", type: "uint256" },
      { name: "defaultConsensusType", type: "uint8" },
      { name: "defaultThreshold", type: "uint256" },
      { name: "defaultTimeout", type: "uint256" },
    ],
  },
  {
    name: "zones",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "zoneId", type: "bytes32" }],
    outputs: [
      { name: "name", type: "string" },
      { name: "dangerLevel", type: "uint256" },
      { name: "controllingFaction", type: "string" },
      { name: "climateState", type: "string" },
    ],
  },
  {
    name: "eventHistory",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [
      { name: "timestamp", type: "uint256" },
      { name: "eventType", type: "string" },
      { name: "description", type: "string" },
      { name: "requestId", type: "uint256" },
    ],
  },
  {
    name: "triggerCooldowns",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "triggerId", type: "bytes32" }],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "factionMorale",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "factionId", type: "string" }],
    outputs: [
      { name: "moraleDelta", type: "int256" },
      { name: "narrative", type: "string" },
      { name: "updatedAt", type: "uint256" },
    ],
  },
  {
    name: "setZone",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "zoneId", type: "bytes32" },
      { name: "name", type: "string" },
      { name: "dangerLevel", type: "uint256" },
      { name: "faction", type: "string" },
    ],
    outputs: [],
  },
  {
    name: "configureManifest",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_manifestHash", type: "bytes32" },
      {
        name: "zones_",
        type: "tuple[]",
        components: [
          { name: "zoneId", type: "bytes32" },
          { name: "name", type: "string" },
          { name: "dangerLevel", type: "uint256" },
          { name: "faction", type: "string" },
        ],
      },
      {
        name: "factions_",
        type: "tuple[]",
        components: [
          { name: "factionId", type: "string" },
          { name: "name", type: "string" },
          { name: "morale", type: "int256" },
          { name: "narrative", type: "string" },
        ],
      },
      {
        name: "triggers_",
        type: "tuple[]",
        components: [
          { name: "triggerId", type: "bytes32" },
          { name: "active", type: "bool" },
          { name: "triggerType", type: "uint8" },
          { name: "emitter", type: "address" },
          { name: "topic0", type: "bytes32" },
          { name: "topic1", type: "bytes32" },
          { name: "gasLimit", type: "uint64" },
          { name: "cooldownSeconds", type: "uint256" },
          { name: "scheduleIntervalSeconds", type: "uint256" },
          { name: "scheduleNextTimestampMs", type: "uint256" },
          { name: "firstStep", type: "uint256" },
          { name: "stepCount", type: "uint256" },
        ],
      },
      {
        name: "steps_",
        type: "tuple[]",
        components: [
          { name: "kind", type: "uint8" },
          { name: "zoneId", type: "bytes32" },
          { name: "factionId", type: "string" },
          { name: "prompt", type: "string" },
          { name: "system", type: "string" },
          { name: "url", type: "string" },
          { name: "selector", type: "string" },
          { name: "payload", type: "bytes" },
        ],
      },
      {
        name: "continuations_",
        type: "tuple[]",
        components: [
          { name: "triggerId", type: "bytes32" },
          { name: "matchValue", type: "string" },
          { name: "nextTriggerId", type: "bytes32" },
          { name: "terminal", type: "bool" },
        ],
      },
    ],
    outputs: [],
  },
  {
    name: "armWorld",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "pauseWorld",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "stopWorld",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "reason", type: "string" }],
    outputs: [],
  },
  {
    name: "fireManualTrigger",
    type: "function",
    stateMutability: "payable",
    inputs: [
      { name: "triggerId", type: "bytes32" },
      { name: "context", type: "string" },
    ],
    outputs: [],
  },
  {
    name: "subscribeTrigger",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "triggerId", type: "bytes32" }],
    outputs: [{ name: "subscriptionId", type: "uint256" }],
  },
  {
    name: "unsubscribeTrigger",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "triggerId", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "manifestHash",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "bytes32" }],
  },
  {
    name: "lifecycleStatus",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint8" }],
  },
  {
    name: "getManifestCounts",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "zoneCount", type: "uint256" },
      { name: "factionCount", type: "uint256" },
      { name: "triggerCount", type: "uint256" },
      { name: "stepCount", type: "uint256" },
    ],
  },
  {
    name: "getManifestTrigger",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "triggerId", type: "bytes32" }],
    outputs: [
      { name: "active", type: "bool" },
      { name: "triggerType", type: "uint8" },
      { name: "emitter", type: "address" },
      { name: "topic0", type: "bytes32" },
      { name: "topic1", type: "bytes32" },
      { name: "gasLimit", type: "uint64" },
      { name: "cooldownSeconds", type: "uint256" },
      { name: "scheduleIntervalSeconds", type: "uint256" },
      { name: "scheduleNextTimestampMs", type: "uint256" },
      { name: "firstStep", type: "uint256" },
      { name: "stepCount", type: "uint256" },
      { name: "subscriptionId", type: "uint256" },
      { name: "lastFiredAt", type: "uint256" },
    ],
  },
  {
    name: "upgradeToAndCall",
    type: "function",
    stateMutability: "payable",
    inputs: [
      { name: "newImplementation", type: "address" },
      { name: "data", type: "bytes" },
    ],
    outputs: [],
  },
  {
    name: "requestAgentDecision",
    type: "function",
    stateMutability: "payable",
    inputs: [
      { name: "triggerId", type: "bytes32" },
      { name: "prompt", type: "string" },
      { name: "system", type: "string" },
      { name: "allowedValues", type: "string[]" },
      { name: "cooldownSeconds", type: "uint256" },
    ],
    outputs: [{ name: "requestId", type: "uint256" }],
  },
  {
    name: "requestLlmToolsChat",
    type: "function",
    stateMutability: "payable",
    inputs: [
      { name: "triggerId", type: "bytes32" },
      { name: "roles", type: "string[]" },
      { name: "messages", type: "string[]" },
      { name: "mcpServerUrls", type: "string[]" },
      { name: "cooldownSeconds", type: "uint256" },
    ],
    outputs: [{ name: "requestId", type: "uint256" }],
  },
  {
    name: "requestJsonOracle",
    type: "function",
    stateMutability: "payable",
    inputs: [
      { name: "triggerId", type: "bytes32" },
      { name: "url", type: "string" },
      { name: "selector", type: "string" },
      { name: "cooldownSeconds", type: "uint256" },
    ],
    outputs: [{ name: "requestId", type: "uint256" }],
  },
  {
    name: "recordChronicleEntry",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "description", type: "string" }],
    outputs: [],
  },
  {
    name: "chronicleFromAgent",
    type: "function",
    stateMutability: "payable",
    inputs: [
      { name: "triggerId", type: "bytes32" },
      { name: "rawEvent", type: "string" },
      { name: "system", type: "string" },
      { name: "cooldownSeconds", type: "uint256" },
    ],
    outputs: [{ name: "requestId", type: "uint256" }],
  },
  {
    name: "requestWebParse",
    type: "function",
    stateMutability: "payable",
    inputs: [
      { name: "triggerId", type: "bytes32" },
      { name: "payload", type: "bytes" },
      { name: "cooldownSeconds", type: "uint256" },
    ],
    outputs: [{ name: "requestId", type: "uint256" }],
  },
  {
    name: "subscribeToEvent",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "emitter", type: "address" },
      { name: "eventSig", type: "bytes32" },
      { name: "gasLimit", type: "uint64" },
    ],
    outputs: [{ name: "subscriptionId", type: "uint256" }],
  },
  {
    name: "unsubscribeFromEvent",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "subscriptionId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "applyClimateResult",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "zoneId", type: "bytes32" },
      { name: "climateState", type: "string" },
    ],
    outputs: [],
  },
  {
    name: "applyConflictOutcome",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "zoneId", type: "bytes32" },
      { name: "outcome", type: "string" },
    ],
    outputs: [],
  },
  {
    name: "updateFactionMorale",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "factionId", type: "string" },
      { name: "moraleDelta", type: "int256" },
      { name: "narrative", type: "string" },
    ],
    outputs: [],
  },
  {
    name: "withdraw",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "ZoneUpdated",
    type: "event",
    inputs: [
      { name: "zoneId", type: "bytes32", indexed: true },
      { name: "newFaction", type: "string", indexed: false },
      { name: "newDanger", type: "uint256", indexed: false },
    ],
  },
  {
    name: "ChronicleAdded",
    type: "event",
    inputs: [
      { name: "eventIndex", type: "uint256", indexed: false },
      { name: "description", type: "string", indexed: false },
    ],
  },
  {
    name: "AgentDecisionRequested",
    type: "event",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "triggerId", type: "bytes32", indexed: true },
    ],
  },
  {
    name: "AgentDecisionReceived",
    type: "event",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "result", type: "string", indexed: false },
    ],
  },
  {
    name: "JsonOracleRequested",
    type: "event",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "triggerId", type: "bytes32", indexed: true },
    ],
  },
  {
    name: "JsonOracleReceived",
    type: "event",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "result", type: "string", indexed: false },
    ],
  },
  {
    name: "NativeAgentRequested",
    type: "event",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "agent", type: "uint8", indexed: true },
      { name: "triggerId", type: "bytes32", indexed: true },
    ],
  },
  {
    name: "ReactivitySubscribed",
    type: "event",
    inputs: [
      { name: "subscriptionId", type: "uint256", indexed: true },
      { name: "eventSig", type: "bytes32", indexed: false },
    ],
  },
  {
    name: "TriggerFired",
    type: "event",
    inputs: [
      { name: "triggerId", type: "bytes32", indexed: true },
      { name: "context", type: "string", indexed: false },
    ],
  },
  {
    name: "ManifestConfigured",
    type: "event",
    inputs: [
      { name: "manifestHash", type: "bytes32", indexed: true },
      { name: "zoneCount", type: "uint256", indexed: false },
      { name: "factionCount", type: "uint256", indexed: false },
      { name: "triggerCount", type: "uint256", indexed: false },
      { name: "stepCount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "LifecycleStatusChanged",
    type: "event",
    inputs: [
      { name: "status", type: "uint8", indexed: true },
      { name: "reason", type: "string", indexed: false },
    ],
  },
  {
    name: "ManifestTriggerSubscribed",
    type: "event",
    inputs: [
      { name: "triggerId", type: "bytes32", indexed: true },
      { name: "subscriptionId", type: "uint256", indexed: true },
      { name: "emitter", type: "address", indexed: true },
      { name: "topic0", type: "bytes32", indexed: false },
    ],
  },
  {
    name: "ManifestTriggerUnsubscribed",
    type: "event",
    inputs: [
      { name: "triggerId", type: "bytes32", indexed: true },
      { name: "subscriptionId", type: "uint256", indexed: true },
    ],
  },
  {
    name: "WorkflowStepRequested",
    type: "event",
    inputs: [
      { name: "triggerId", type: "bytes32", indexed: true },
      { name: "stepIndex", type: "uint256", indexed: true },
      { name: "kind", type: "uint8", indexed: true },
      { name: "requestId", type: "uint256", indexed: false },
    ],
  },
  {
    name: "WorkflowCompleted",
    type: "event",
    inputs: [
      { name: "triggerId", type: "bytes32", indexed: true },
      { name: "result", type: "string", indexed: false },
    ],
  },
  {
    name: "DecisionContinuationMatched",
    type: "event",
    inputs: [
      { name: "triggerId", type: "bytes32", indexed: true },
      { name: "nextTriggerId", type: "bytes32", indexed: true },
      { name: "matchValue", type: "string", indexed: false },
      { name: "terminal", type: "bool", indexed: false },
    ],
  },
  {
    name: "FactionMoraleUpdated",
    type: "event",
    inputs: [
      { name: "factionId", type: "string", indexed: true },
      { name: "moraleDelta", type: "int256", indexed: false },
      { name: "narrative", type: "string", indexed: false },
    ],
  },
  { type: "receive", stateMutability: "payable" },
] as const;

export const REGISTRY_ABI = [
  {
    name: "deployWorld",
    type: "function",
    stateMutability: "payable",
    inputs: [
      { name: "name", type: "string" },
      { name: "template", type: "string" },
    ],
    outputs: [{ type: "address" }],
  },
  {
    name: "getWorldsByOwner",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [
      {
        type: "tuple[]",
        components: [
          { name: "worldAddress", type: "address" },
          { name: "name", type: "string" },
          { name: "template", type: "string" },
        ],
      },
    ],
  },
  {
    name: "getAllWorlds",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {
        type: "tuple[]",
        components: [
          { name: "worldAddress", type: "address" },
          { name: "name", type: "string" },
          { name: "template", type: "string" },
        ],
      },
    ],
  },
  {
    name: "registrationFee",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "worldImplementation",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    name: "setWorldImplementation",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "_worldImplementation", type: "address" }],
    outputs: [],
  },
  {
    name: "upgradeToAndCall",
    type: "function",
    stateMutability: "payable",
    inputs: [
      { name: "newImplementation", type: "address" },
      { name: "data", type: "bytes" },
    ],
    outputs: [],
  },
  {
    name: "WorldRegistered",
    type: "event",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "worldAddress", type: "address", indexed: true },
      { name: "name", type: "string", indexed: false },
      { name: "template", type: "string", indexed: false },
    ],
  },
] as const;
